version: "3.7"

services:
  knowledge-base:
    build:
      context: .
      args:
        - PERSONAL_ACCESS_TOKEN=${PERSONAL_ACCESS_TOKEN}
    container_name: knowledge-base
    restart: always
    networks:
      - reverse-proxy
    expose:
      - 4567

networks:
  reverse-proxy:
    name: nginx_default
    external: true
