version: "3.7"

services:
  gollum:
    build:
      context: .
    environment:
      - GITHUB_KEY=${GITHUB_KEY}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - OMNIGOLLUM_AUTHORIZED_USERS=${OMNIGOLLUM_AUTHORIZED_USERS}
    restart: always
    ports:
      - "8067:9292/tcp"
